fixed CI/CD

diff --git a/.github/workflows/cd_backend.yml b/.github/workflows/cd_backend.yml
--- a/.github/workflows/cd_backend.yml
+++ b/.github/workflows/cd_backend.yml
@@ -24,9 +24,14 @@ jobs:
           file: ./docker/Dockerfile.backend
           push: true
           tags: ${{ secrets.DOCKER_USERNAME }}/backend:${{ github.sha }}
-      - name: Deploy to the VM
-        run: |
-          echo "${{ secrets.MY_SSH_TODO }}" > ~/ssh_key
-          mkdir -p /home/ubuntu/.ssh
-          chmod 700 /home/ubuntu/.ssh
-          ssh -o StrictHostKeyChecking=no -i ~/ssh_key cocane@34.93.115.4 -t "docker stop user_backend && docker run --name user_backend -d -p 3001:3001 cocane/backend:${{ github.sha }}"
+      - name: Deploy to Remote Server
+          run: |
+            echo "${{ secrets.MY_SSH_TODO }}" > ssh_key
+            chmod 600 ssh_key
+
+            # Optional: Clean up existing container
+            ssh -o StrictHostKeyChecking=no -i ssh_key cocane@34.93.115.4 "docker stop user_backend || true && docker rm user_backend || true"
+
+            # Run new container
+            ssh -o StrictHostKeyChecking=no -i ssh_key cocane@34.93.115.4 \
+              "docker run --name user_backend -d -p 3001:3001 ${{ secrets.DOCKER_USERNAME }}/backend:${{ github.sha }}"
